# Generated by Django 5.2.3 on 2025-06-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('email_port', models.IntegerField(default=587)),
                ('email_host_user', models.EmailField(max_length=254)),
                ('email_host_password', models.TextField()),
                ('recipient_email', models.EmailField(max_length=254)),
                ('use_tls', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('company_logo', models.FileField(blank=True, null=True, upload_to='logo/')),
                ('manipulation_threshold', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('start_ticket_number', models.CharField(default=0, unique=True)),
                ('payment_type', models.CharField(max_length=50)),
                ('weighing_method', models.CharField(choices=[('manual', 'Manual')], max_length=50)),
                ('weighing_unit', models.CharField(choices=[('kg', 'Kilogram'), ('ton', 'Ton')], default='kg', max_length=50)),
            ],
        ),
    ]
