# Generated by Django 5.2.3 on 2025-06-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_expiry',
            field=models.DateField(null=True),
        ),
    ]
