# Generated by Django 5.2.3 on 2025-06-19 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.driver'),
        ),
        migrations.CreateModel(
            name='BlockedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manipulative_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('manipulative_date', models.DateTimeField(auto_now_add=True)),
                ('is_blocked', models.BooleanField(default=True)),
                ('unblock_date', models.DateTimeField(blank=True, null=True)),
                ('unblock_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('blocked', 'Blocked'), ('unblocked', 'Unblocked')], default='blocked', max_length=10)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.driver')),
                ('manipulative_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manipulated_blocks', to=settings.AUTH_USER_MODEL)),
                ('unblock_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unblocked_blocks', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
    ]
