# Generated by Django 5.2.3 on 2025-06-22 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_blockedvehicle_unblock_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedvehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.driver'),
        ),
    ]
