# Generated by Django 5.2.3 on 2025-06-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manager', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('joined_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('sector', models.CharField(choices=[('طيور', 'طيور'), ('زراعة', 'زراعة'), ('اغنام', 'اغنام')], max_length=10)),
                ('type', models.CharField(choices=[('حي', 'حي'), ('نافق', 'نافق')], max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('manufacturer', models.CharField(blank=True, max_length=250, null=True)),
                ('model', models.CharField(blank=True, max_length=250, null=True)),
                ('front_camera_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('front_camera_port', models.CharField(blank=True, max_length=100, null=True)),
                ('rear_camera_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('rear_camera_port', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('connection_type', models.CharField(choices=[('serial', 'Serial'), ('tcp', 'TCP')], default='tcp', max_length=10)),
                ('ip', models.CharField(blank=True, max_length=250, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('delay', models.FloatField(blank=True, choices=[(1, '1 '), (0.75, '0.75'), (0.5, '0.5'), (0.25, '0.25'), (0.1, '0.1')], default=0.5, null=True)),
                ('bits_number', models.IntegerField(choices=[(5, '5'), (6, '6'), (7, '7'), (8, '8'), (16, '16'), (32, '32'), (64, '64'), (128, '128'), (256, '256'), (512, '512'), (1024, '1024')])),
                ('serial_port', models.CharField(blank=True, choices=[('COM1', 'COM1'), ('COM2', 'COM2'), ('COM3', 'COM3'), ('COM4', 'COM4'), ('COM5', 'COM5'), ('COM6', 'COM6')], max_length=10, null=True)),
                ('baudrate', models.IntegerField(blank=True, choices=[(110, '110'), (300, '300'), (600, '600'), (1200, '1200'), (2400, '2400'), (4800, '4800'), (9600, '9600'), (14400, '14400'), (19200, '19200'), (38400, '38400')], default=9600, null=True)),
                ('parity', models.CharField(blank=True, choices=[('none', 'None'), ('even', 'Even'), ('odd', 'Odd'), ('mark', 'Mark'), ('space', 'Space')], max_length=10, null=True)),
                ('stop_bits', models.FloatField(blank=True, choices=[(1, '1'), (1.5, '1.5'), (2, '2')], null=True)),
                ('flow_control', models.CharField(blank=True, choices=[('none', 'None'), ('hardware', 'Hardware'), ('Xon/Xoff', 'Xon/Xoff')], max_length=20, null=True)),
                ('weight_start_index', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_end_index', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
