# Generated by Django 5.2.3 on 2025-06-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('sector', models.CharField(choices=[('طيور', 'طيور'), ('زراعة', 'زراعة'), ('اغنام', 'اغنام')], max_length=10)),
                ('type', models.CharField(choices=[('حي', 'حي'), ('نافق', 'نافق')], max_length=5, null=True)),
            ],
        ),
    ]
