# Generated by Django 5.2.3 on 2025-06-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_scale_port'),
    ]
