# Generated by Django 5.2.3 on 2025-06-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
