# Generated by Django 5.2.3 on 2025-06-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scale',
            name='port',
        ),
    ]
