# Generated by Django 5.2.3 on 2025-06-22 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_item'),
        ('vehicles', '0006_alter_blockedvehicle_unblock_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('ticket_type', models.CharField(choices=[('IN', 'التفريغ'), ('OUT', 'المبيعات')], default='IN', max_length=10)),
                ('first_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('first_weight_date', models.CharField(blank=True, max_length=250, null=True)),
                ('second_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('second_weight_date', models.CharField(blank=True, max_length=250, null=True)),
                ('trailer_first_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('trailer_second_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('trailer_plate_number', models.CharField(blank=True, max_length=10, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('farm', models.CharField(blank=True, max_length=50, null=True)),
                ('boxes_number', models.IntegerField(blank=True, null=True)),
                ('birds_number', models.IntegerField(blank=True, null=True)),
                ('gas_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.client')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.driver')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.item')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.scale')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
    ]
